name: Pop Empire

kramdown:
  highlighter: none
  syntax_highlighter_opts:
    disable: true

collections:

  chords:
    output: true
    permalink: /:collection/:slug/

  lyrics:
    output: true
    permalink: /:collection/:slug/

  tabs:
    output: true
    permalink: /:collection/:path/
