name: Pop Empire
url: https://www.popempire.com

kramdown:
  highlighter: none
  syntax_highlighter_opts:
    disable: true

collections:

  lyrics:
    output: true
    permalink: /:collection/:slug/
